/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.codelife;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    public String solution(String[] participant, String[] completion) {
        Arrays.sort(participant);
        Arrays.sort(completion);

        int index = Arrays.mismatch(participant, completion);

        return participant[index];
    }

    @Test void simpleTest() {
        assertEquals(solution(
                new String[]{"leo", "kiki"},
                new String[]{"leo"}
        ), "kiki");
    }

    @Test void manyParticipants() {
        assertEquals(solution(
                new String[]{"leo", "kiki", "chichi", "shushu", "nana", "ella"},
                new String[]{"leo", "kiki", "chichi", "shushu", "nana"}
        ), "ella");
    }

    @Test void duplicateNames() {
        assertEquals(solution(
                new String[]{"leo", "kiki", "kiki"},
                new String[]{"leo", "kiki"}
        ), "kiki");
    }
}
