# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem 'guard' # NOTE: this is necessary in newer versions
  gem 'guard-minitest'
  gem 'minitest-reporters'
end
