/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swing;

import javax.swing.*;

// 한 일
// - 화면 추가 -> 크기 설정 및 타이틀 추가
// - 화면을 추가하면서 각 단계마다 피드백 받는 것 확인하기
// - 라벨 추가
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }

    private void run() {
        JFrame frame = new JFrame();

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 300);
        frame.setTitle("Hello World");

        JLabel label = new JLabel("Hello, World!");
        frame.add(label);

        frame.setVisible(true);
    }
}
