/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testSlice() {
        assertThat(slice(intArrayOf(1, 2, 3, 4, 5), 1, 3))
                .isEqualTo(intArrayOf(1, 2, 3))

        assertThat(slice(intArrayOf(3, 2, 4, 6, 8), 1, 5))
                .isEqualTo(intArrayOf(3, 2, 4, 6, 8))

        assertThat(slice(intArrayOf(1, 3, 6, 9), 2, 4))
                .isEqualTo(intArrayOf(3, 6, 9))
    }

    @Test fun testSort() {
        assertThat(sort(intArrayOf(3, 2, 4, 6)))
                .isEqualTo(intArrayOf(2, 3, 4, 6))

        assertThat(sort(intArrayOf(7, 1, 3, 5)))
                .isEqualTo(intArrayOf(1, 3, 5, 7))
    }

    @Test fun testSolveOneCommand() {
        assertThat(solveOneCommand(intArrayOf(3, 5, 4, 2, 1), intArrayOf(1, 3, 2)))
                .isEqualTo(4)

    }

    @Test fun testSolution() {
        val instance = Solution()
        assertThat(instance.solution(
                intArrayOf(3, 5, 4, 2, 1),
                arrayOf(intArrayOf(1, 3, 2), intArrayOf(2, 5, 4))
        )).isEqualTo(intArrayOf(4, 5))
    }
}
