/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    Integer plusOne(Integer number) {
        return number + 1;
    }

    @Test void appHasAGreeting() {
        assertEquals(plusOne(1), 2);
    }
}
