/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.tddexercise;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test
    void testWorks() {
        assertEquals(1 + 1, 2);
    }
}
