/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package customCollector;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertThat(1 + 1).isEqualTo(2);
    }
}
