/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.telephonebook;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {
    boolean solution(String[] phoneBook) {
        var tree = new Trie();

        for (String phoneNumber : phoneBook) {
            tree.insert(phoneNumber);
        }

        return Arrays.stream(phoneBook).noneMatch(tree::startsWith);
    }

    @Test void examples() {
        assertThat(solution(new String[]{"119", "97674223", "1195524421"})).isFalse();
        assertThat(solution(new String[]{"123","456","789"})).isTrue();
        assertThat(solution(new String[]{"12","123","1235","567","88"})).isFalse();
    }
}
