/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package swing;

import org.assertj.swing.core.GenericTypeMatcher;
import org.assertj.swing.fixture.FrameFixture;
import org.assertj.swing.junit.testcase.AssertJSwingJUnitTestCase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.awt.*;

import static org.assertj.swing.finder.WindowFinder.findFrame;
import static org.assertj.swing.launcher.ApplicationLauncher.application;

class AppTest extends AssertJSwingJUnitTestCase {
    FrameFixture frame;

    @BeforeEach
    public void setup() throws Exception {
        onSetUp();
    }

    @Test
    public void testShowingTitle() {
        frame.requireTitle("Hello World");

        frame.label().requireText("Hello, World!");
    }

    @Override
    protected void onSetUp() {
        setUpRobot();

        Character.digit('A', 16);

        application(App.class).start();

        frame = findFrame(new GenericTypeMatcher<Frame>(Frame.class) {
            @Override
            protected boolean isMatching(Frame frame) {
                return frame.isShowing();
            }
        }).using(robot());
    }
}
