/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.briansworry;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    String findWord(String sentence, List<String> words) {
        if (sentence.length() == 0) {
            return String.join(" ", words);
        }

        // Rule 1.
        char first = sentence.charAt(0);
        if (Character.isLowerCase(first)) {
            int lastIndex = sentence.lastIndexOf(first);
            String word = sentence.substring(1, lastIndex);
            words.add(word);

            return findWord(
                    sentence.substring(lastIndex + 1),
                    words
            );
        }

        // Rule 2.
        if (sentence.length() > 2 && Character.isLowerCase(sentence.charAt(1))) {
            int lastIndex = sentence.lastIndexOf(sentence.charAt(1));
            String word = sentence.substring(0, lastIndex + 2).replaceAll("[a-z]", "");
            words.add(word);

            return findWord(
                    sentence.substring(lastIndex + 2),
                    words
            );
        }

        return "invalid";
    }

    @Test
    void simple() {
        assertEquals(
                findWord("cHELLOcbWORLDb", new ArrayList<>()),
                "HELLO WORLD"
        );
        assertEquals(
                findWord("HsEsLsLsObWORLDb", new ArrayList<>()),
                "HELLO WORLD"
        );
    }

    @Test
    void sample() {
        assertEquals(
                findWord("HaEaLaLaObWORLDb", new ArrayList<>()),
                "HELLO WORLD"
        );

        assertEquals(
                findWord("SpIpGpOpNpGJqOqA", new ArrayList<>()),
                "SIGONG JOA"
        );

        assertEquals(
                findWord("AxAxAxAoBoBoB", new ArrayList<>()),
                "invalid"
        );
    }
}
