/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exercise.tdd;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testIsWorking() {
        assertThat(1 + 1).isEqualTo(2);
    }
}
