# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

group :development do
  gem 'guard' # NOTE: this is necessary in newer versionsxwxw
  gem 'guard-minitest'
  gem 'minitest-reporters'
  gem 'redgreen'
end
