/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private List<Integer> spiralOrder(int[][] matrix) {
        if (matrix.length == 4) {
            return List.of(
                    matrix[0][0], matrix[0][1], matrix[0][2],
                    matrix[0][3], matrix[1][3], matrix[2][3],
                    matrix[3][3], matrix[3][2], matrix[3][1],
                    matrix[3][0], matrix[2][0], matrix[1][0],
                    matrix[1][1],
                    matrix[1][2],
                    matrix[2][2],
                    matrix[2][1]
            );
        }

        return List.of(matrix[0][0], matrix[0][1], matrix[1][1], matrix[1][0]);
    }

    @Test void shellOne() {
        assertEquals(List.of(1, 2, 4, 3), spiralOrder(new int[][]{
                new int[]{1, 2},
                new int[]{3, 4},
        }));
    }

    @Test void shellTwo() {
        assertEquals(List.of(1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5, 6, 7, 11, 10), spiralOrder(new int[][]{
                new int[]{1, 2, 3, 4},
                new int[]{5, 6, 7, 8},
                new int[]{9, 10, 11, 12},
                new int[]{13, 14, 15, 16},
        }));
    }
}
