/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coding.interview.java;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test
    void singleNumber() {
        assertTrue(parity(3));
        assertTrue(parity(5));

        assertFalse(parity(4));
        assertFalse(parity(7));
    }

    private boolean parity(int i) {
        int sumOfNoneZeros = Stream.iterate(i, k -> k > 0, k -> k >> 1)
                .mapToInt(k -> k & 1).sum();
        return sumOfNoneZeros % 2 == 0;
    }

    private boolean parity01(int i) {
        return Arrays.stream(Integer.toBinaryString(i)
                        .split(""))
                .map(Integer::parseInt)
                .reduce(0, Integer::sum) % 2 == 0;
    }

    private boolean parity02(int i) {
        return Arrays.stream(Integer.toBinaryString(i)
                        .split(""))
                .map(Integer::parseInt)
                .mapToInt(j -> j).sum() % 2 == 0;

    }
}
