/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

fun slice(array: IntArray, i: Int, j: Int): IntArray {
    return array.sliceArray(IntRange(i - 1, j - 1))
}

fun sort(array: IntArray): IntArray {
    return array.sortedArray()
}

fun solveOneCommand(target: IntArray, command: IntArray): Int {
    val (i, j, k) = command

    return target
            .sliceArray(IntRange(i - 1, j - 1))
            .sortedArray()[k - 1]
}

class Solution {
    fun solution(target: IntArray, commands: Array<IntArray>): IntArray {
        return commands
                .map { command -> solveOneCommand(target, command) }
                .toIntArray()
    }
}

fun main() {
}
