/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gringrape.codelife;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertEquals(1 + 1, 2);
    }
}
