/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package coding.dojo

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    fun sum(a: Int, b: Int): Int {
        return a + b
    }

    @Test
    fun appHasAGreeting() {
        assertEquals(3, sum(1, 2))
    }
}
